### ISSUE TITLE
Getting ember-validations to work with Ember 1.13.0-beta.2

### ISSUE THREAD

**Issue by amk221** [DockYard/ember-validations#312] opened 2015-06-07 11:42 UTC
With a fresh app, I get:

`Assertion Failed: Expected service:validations to resolve to an Ember.Service but instead it was (unknown mixin)`

Is it possible to use ember-validations with this version of Ember?

**Comment by selvaa89** [comment] 2015-06-08 12:33
I am also getting same error.

**Comment by amk221** [comment] 2015-06-11 09:59
Would some feedback on this just so I can plan ahead 
Thanks, much appreciated!

**Comment by QuantumInformation** [comment] 2015-06-11 11:08
Also get this error

**Comment by selvaa89** [comment] 2015-06-12 08:32
I think the issue is fixed. https://github.com/dockyard/ember-validations/pull/307
It would be nice to know when this will be released.

**Comment by ppcano** [comment] 2015-06-23 09:25
@bcardarella  may it be possible to release a new version?

**Comment by elliotlarson** [comment] 2015-07-28 22:11
:+1:

**Comment by omouse** [comment] 2016-01-08 20:46
how did you get it installed at all? I'm having issues with getting it installed with 1.12.0

**Comment by martndemus** [comment] 2016-08-12 18:56
I am going to close this issue for now, feel free to reopen this issue if you feel like it's still relevant and we should take a look at it.

**Closed by martndemus** 2016-08-12 18:56 UTC
