### ISSUE TITLE
Setting read only property isValid raises an exception with Ember Data 

### ISSUE THREAD

**Issue by delwyn** [DockYard/ember-validations#26] opened 2013-06-18 15:27 UTC
When using ember-validations with the latest Ember and Ember Data, the promise returned by .validate() always gets rejected with the following rejection message:

    Cannot Set: isValid on: <App.Contact:ember927:null>

The validations are working correctly up until it attempts to the the isValid property.

**Comment by josemarluedke** [comment] 2015-01-22 21:24
I'm having a problem that I think may be related to this.

We are using ember-data and ember-validations together, that means, back-end validations and front-end validations. My problem is that the `isValid` never changes to `true`.

I guess it's because of this: 
```
 isValid: Ember.computed.empty('errors.[]'),
```
Defined at: https://github.com/dockyard/ember-validations/blob/master/addon/validators/base.js#L37

Given that ember-data errors always returns an array with the properties and inside would have an empty array if that field is valid. Example: 

```javascript
user.get('errors.[]');
=> Object { name: Getter, birthDate: Getter }

user.get('errors.name');
=> Array [  ]
```

I'm not sure if this is actually where the problem is, I see the issue #206 that might solve the problem as well. Any ideas of how to fix it, I would love to open a PR.

**Comment by martndemus** [comment] 2016-08-12 18:42
I am going to close this issue for now, feel free to reopen this issue if you feel like it's still relevant and we should take a look at it.

**Closed by martndemus** 2016-08-12 18:42 UTC
