### ISSUE TITLE
Cannot read property 'lookup' of undefined w/ the latest 2.0 build

### ISSUE THREAD

**Issue by toranb** [DockYard/ember-validations#247] opened 2015-02-01 20:24 UTC
Team

First off -thanks for such a great OSS project! I truly stand on the shoulders of giants today!

I'm using the latest build w/ ember-cli (here is my package.json)

```
    "ember-validations": "2.0.0-alpha.2",
```

The problem statement: I get an explosion trying to boot a simple ember-cli example app. I'm trying to verify if I missed a step/ or if the README is out of date. I hope this is a helpful contribution to those looking at the library in the near future.

here is the code that blew up in ember-validations:

```js
var lookupValidator = function(validatorName) {
      var container = get(this, 'container');
      var service = container.lookup('service:validations');  //BOOM container is undefined
}
```

Here is my simple model (following the README as of today)

```js
import EmberValidations from 'ember-validations';

export default Ember.Object.extend(EmberValidations.Mixin, {
      wat: '',
      validations: {
        wat: { presence: true }
      }
});
```

Here is my controller where I intend to invoke the validate method

```js
export default Ember.ObjectController.extend({
    actions: {
        save: function() {
            var model = this.get('model');
            model.validate().then(null, function() {
                console.log('hello world');
            });
        }
    }
});
```

In my route I simply return a new model so I get a new/fresh form each time the user enters the route

```js

export default Ember.Route.extend({
    model: function() {
        return User.create();
    }
});

```

Thanks again for supporting such a great community project!

**Comment by toranb** [comment] 2015-02-01 20:26
Note: I do see that in the tests you provide a container (shown below). How should/ do production apps do this exactly (or is this just just a test-helper of some kind?)

https://github.com/dockyard/ember-validations/blob/master/tests/unit/errors-test.js#L12

**Comment by bcardarella** [comment] 2015-02-01 21:34
1. What type of object are you mixing validations into? By default the standard objects in ember-cli, assuming you have them in the proper directories, should have `container` injected into them.
2. Is this a unit test? Some unit test objects don't have container and will have to be worked around for now until I can develop a better solution

**Comment by toranb** [comment] 2015-02-01 22:28
1. It's a vanilla ember object inside the models folder (no ember-data in this ember-cli project)

2. I'm currently trying to boot the app in browser (not a unit test currently but I do plan to test this also and looked over your tests for some guidance).

thanks for the quick reply @bcardarella

**Comment by quaertym** [comment] 2015-02-06 02:19
I also hit this issue now and then. @bcardarella do you think that [this function] (https://github.com/dockyard/ember-validations/blob/master/addon/mixin.js#L31-70) can be replaced by an initializer?

**Comment by simonihmig** [comment] 2015-02-07 12:52
Same case here, objects to be validated in unit tests, but also plain `Ember.Object`s fail because of missing container. 

@bcardarella regarding 1.: you probably know that only objects created by the container will have the `container` property set. When using plain `Ember.Object`s not generated by a container factory, but simply imported with `import object from 'path/to/object';` those will be missing the container as well!

My hope would be sore something like this to work out-of-the-box:
```js 
var model = Ember.Object.extend(EmberValidations.Mixin,{
            test: null,
            validations: {
                test: {
                    presence: true
                }
            }
        }).create(),
```

**Comment by Kira2** [comment] 2015-02-10 16:46
Hi,

First, I would like also to thank the team for such a great projet. I faced the same problem, and this is my quick simple workaround. I am a new developer on Ember, so I cannot guarantee that this is the best thing to do. It is only to share it with other developers.

As the container is automatically injected to the route when you use ember-cli, you can do this when you create your model into it:

```
export default Ember.Route.extend({
    model: function() {
        return User.create({
            container: this.get('container')
        });
    }
});
```

**Comment by green-arrow** [comment] 2015-02-13 15:41
The solution provided by @Kira2 is a good workaround for now. Any idea on how difficult it would be to fix the root cause of this bug, @bcardarella?

**Comment by JordyLangen** [comment] 2015-02-17 11:14
I use the following solution since I already had a base model:
```javascript
export default Ember.Object.extend({
    // we need to do this for ember-validations
    container: App.__container__
});
```

```javascript
import BaseModel from 'app/models/base';
export default BaseModel.extend(EmberValidations.Mixin, {
    
    ...
});
```

You would only need to remove that single statement when it is fixed.
I guess you could fix this by using the global container on the application object, which is rather nasty.

**Comment by green-arrow** [comment] 2015-02-17 12:52
@JordyLangen where does your reference to `App` come from, since it looks like you're using ember-cli?

**Comment by JordyLangen** [comment] 2015-02-17 17:54
That would be 
```javascript
import App from 'my-app-name/app';
```

**Comment by JordyLangen** [comment] 2015-02-17 18:00
@green-arrow That is just the name of your app (the object hosting your application, living on `window`). I haven't found a way to import it yet. It's a rather nasty fix, but it's a fix that I can remove quickly when no longer needed.

**Comment by green-arrow** [comment] 2015-02-19 13:49
@JordyLangen I may be missing something obvious, but I don't have my application living on `window`. Does ember-cli put your application on `window` behind the scenes?

**Comment by green-arrow** [comment] 2015-02-19 13:54
It doesn't look like ember-cli puts the application on `window` anymore. However, @rwjblue made [this nice little addon](https://github.com/ember-cli/ember-export-application-global) that will do it for you. If using ember-cli, you can use that to get to the global application and use the method @JordyLangen recommended.

**Comment by ferenc-radius** [comment] 2015-02-20 12:34
Is there a proper fix on the way? Otherwise I will fork and work on it

**Comment by kennethkalmer** [comment] 2015-02-24 05:42
Another way to get access to the app instance is to import it:

```js
import App from 'my-namespace/app';
```

I agree that using plain Ember objects with validations is useful, even though they don't have a container set. Maybe the controller is the better place though, like implied in all the examples in the README. Just like Rails moved from `attr_accessible` to _strong params_, the controller might be the better place for the validations since different contexts might demand different validations on the same object

**Comment by AyKarsi** [comment] 2015-07-07 11:24
My workaround is to create an initializer which adds the container to Ember-Validations:

```
import EmberValidations from 'ember-validations';
var alreadyRun = false;
export function initialize(container) {
  if (alreadyRun) {
        return;
    } else {
        alreadyRun = true;
    }

    EmberValidations.reopen({
      container:container, // the magic part..
    });
}

export default {
  name: 'reopen-validations',
  initialize: initialize
};

```

**Comment by beatle** [comment] 2015-07-07 22:39
@AyKarsi, Thank you a lot!
It fits perfect to my needs.

**Comment by beatle** [comment] 2015-07-09 22:15
... But it breaks my integration tests :) It'id broken because initializers are not invoked for integration tests. 
Resumed looking for better solution.

**Comment by AyKarsi** [comment] 2015-07-10 07:47
strange.. integration tests work for me. or do you mean acceptance tests?

**Comment by beatle** [comment] 2015-07-13 21:17
@AyKarsi my fault. I've put initializer in app/ folder instead of addon/. So initializer hasn't been included on addon tests run. 
Thank you again and sorry for the buzz.

**Comment by kkdashu** [comment] 2015-08-15 04:04
export default Ember.Object.extend({
    // we need to do this for ember-validations
    container: window.'myapp'.__container__
});

**Comment by AO16** [comment] 2015-10-06 19:56
Really don't want to have to include `container` on my object. Seems really unnecessary. Any one else have any other workarounds?

**Comment by AO16** [comment] 2015-10-07 13:16
Using on `Ember.Object` is included in the docs. I feel like at the very least this should be removed from the docs for the time being.

**Comment by AO16** [comment] 2015-10-07 17:26
I came up with a bit of a workaround. I just over rode the `buildValidators` call.
```javascript
	buildValidators() {
		if (this.get('container')) this.set('container', App.__container__);
		return this._super(...arguments);
	},
```

**Comment by sir-dunxalot** [comment] 2016-03-07 01:49
For anyone dealing with this issue in unit tests, this was my solution:

```js
// some-addon/tests/unit/components/form.js

import startApp from '../../helpers/start-app';

test('Some test requiring the container', function() {
  const App = startApp(null);

  const ComponentFormObject = Ember.Component.extend({
    container: App.__container__,
  });
});
```

**Comment by martndemus** [comment] 2016-08-12 18:52
I am going to close this issue for now, feel free to reopen this issue if you feel like it's still relevant and we should take a look at it.

**Closed by martndemus** 2016-08-12 18:52 UTC
